### ISSUE TITLE
Histogram visualisation of use per time

### ISSUE THREAD

**Issue by woodsp** [davemfish/trails-viz#8]
I'm keen to see a histogram(s) alongside the line plot that shows total (or average?) user days per year, month of year, and day of week.  This could be several individual plots or include a feature for users to select the time (day, month, year).

**Comment by davemfish** [comment]
AW requested the following to be displayed for a selected trail. I think this will largely be satisfied by the histograms:
summer visitation stats June-Labor Day
Weekday daily mean use: ###
Weekend daily mean use ###
Max daily:
Min daily
Etc

**Comment by woodsp** [comment]
I had the impression during our convo on Monday that AW wanted these stats to appear in the pop-up box on map, which I thought was an interesting idea.

**Comment by davemfish** [comment]
Yeah, he did mention a pop-up. In my opinion those get very cluttered quickly and obscure the rest of the map -- sometimes even obscuring the feature you click on -- so I probably prefer this "pop-up" info goes in an area outside the map. But also, I figure some of this is redundant with the histogram's info, so that's why I mentioned it on this thread.

**Comment by woodsp** [comment]
All good points; I agree.
